name: optris_connect_sdk
description: Optris ffi adater for Optris Connect SDK
version: 1.0.0
repository: "https://github.com/TomJumel/dart_optris_sdk"

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  path: ^1.8.0
  ffi: ^1.2.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
